---
# Audit repositories in this org.

name: Audit Repos
permissions: {}

on:
  schedule:
    - cron: '00 09 * * *'
  workflow_dispatch:

jobs:
  audit:
    name: Audit Repos
    runs-on: ubuntu-latest
    steps:
      - name: Audit
        uses: LizardByte/actions/actions/audit_repos@09a6e10dc8175f2933c20bdf35fde0a193a9c00e  # v2026.129.194351
        with:
          allowEmptyDescription: true
          checkDiscussions: org
          orgDiscussionsRepo: community
          token: ${{ secrets.GH_BOT_TOKEN }}
