---
# Audit repositories in this org.

name: Audit Repos
permissions: {}

on:
  schedule:
    - cron: '00 09 * * *'
  workflow_dispatch:

jobs:
  audit:
    name: Audit Repos
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - name: Audit
        uses: LizardByte/actions/actions/audit_repos@70bb8d394d1c92f6113aeec6ae9cc959a5763d15  # v2026.227.200013
        with:
          allowEmptyDescription: true
          checkDiscussions: org
          orgDiscussionsRepo: community
          token: ${{ secrets.GH_BOT_TOKEN }}
