---
# Audit repositories in this org.

name: Audit Repos
permissions: {}

on:
  schedule:
    - cron: '00 09 * * *'
  workflow_dispatch:

jobs:
  audit:
    name: Audit Repos
    runs-on: ubuntu-latest
    steps:
      - name: Audit
        uses: LizardByte/actions/actions/audit_repos@6be4ea62064b64957aa880252fe353cd65bcdef7  # v2026.214.14019
        with:
          allowEmptyDescription: true
          checkDiscussions: org
          orgDiscussionsRepo: community
          token: ${{ secrets.GH_BOT_TOKEN }}
