---
# This workflow is intended to work with all our organization Node projects.

# This workflow will run tests using node and then create a draft release on GitHub for push events to master.

name: CI-Node (called)
permissions:
  contents: read

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        description: 'Codecov token to use for the workflow.'
        required: false
      GH_TOKEN:
        description: 'GitHub bot token to use for the workflow.'
        required: false

jobs:
  setup_release:
    name: Setup Release
    outputs:
      publish_release: ${{ steps.setup_release.outputs.publish_release }}
      release_body: ${{ steps.setup_release.outputs.release_body }}
      release_generate_release_notes: ${{ steps.setup_release.outputs.release_generate_release_notes }}
      release_tag: ${{ steps.setup_release.outputs.release_tag }}
      release_version: ${{ steps.setup_release.outputs.release_version }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Release
        id: setup_release
        uses: LizardByte/actions/actions/release_setup@v2025.1028.23217
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs:
      - setup_release
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: latest

      - name: Set version
        env:
          RELEASE_VERSION: ${{ needs.setup_release.outputs.release_version }}
        id: version
        run: |
          VERSION=${RELEASE_VERSION}
          if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            VERSION=$(date +%Y.%m%d.%H%M%S)
          fi

          echo "RELEASE_VERSION=${VERSION}" >> "${GITHUB_OUTPUT}"

      - name: Update package.json
        env:
          RELEASE_VERSION: ${{ steps.version.outputs.RELEASE_VERSION }}
        run: npm version "${RELEASE_VERSION}" --no-git-tag-version

      - name: Install dependencies
        run: npm install

      - name: Test
        id: test
        env:
          FORCE_COLOR: true
        run: npm test

      - name: Build
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: npm run build

      - name: Publish (dry run)
        run: npm publish --dry-run

      - name: Upload test coverage
        # any except canceled or skipped
        if: >-
          always() &&
          (steps.test.outcome == 'success' || steps.test.outcome == 'failure') &&
          startsWith(github.repository, 'LizardByte/')
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de  # v5.5.2
        with:
          disable_search: true
          fail_ci_if_error: true
          files: ./coverage/coverage-final.json
          report_type: coverage
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

      - name: Upload test results
        # any except canceled or skipped
        if: >-
          always() &&
          (steps.test.outcome == 'success' || steps.test.outcome == 'failure') &&
          startsWith(github.repository, 'LizardByte/')
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de  # v5.5.2
        with:
          fail_ci_if_error: true
          files: ./junit.xml,!./cache
          report_type: test_results
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  release:
    if: needs.setup_release.outputs.publish_release == 'true'
    needs:
      - setup_release
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: action
        uses: LizardByte/actions/actions/release_create@v2025.1028.23217
        with:
          allowUpdates: false
          artifacts: ''
          body: ${{ needs.setup_release.outputs.release_body }}
          draft: true
          generateReleaseNotes: ${{ needs.setup_release.outputs.release_generate_release_notes }}
          name: ${{ needs.setup_release.outputs.release_tag }}
          prerelease: true
          tag: ${{ needs.setup_release.outputs.release_tag }}
          token: ${{ secrets.GH_TOKEN }}
