---
name: Update NPM (called)
permissions:
  contents: read
  id-token: write  # required for provenance and OIDC
  packages: write

on:
  workflow_call:
    inputs:
      release_version:
        description: 'Version to publish (v prefix will be stripped automatically).'
        required: true
        type: string

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    environment:
      name: ${{ matrix.environment }}
      url: ${{ steps.environment.outputs.url }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - registry-url: "https://npm.pkg.github.com"
            environment: npm-gpr
            extra-args: ""
          - registry-url: "https://registry.npmjs.org"
            environment: npmjs
            extra-args: "--provenance --access public"
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1

      - name: Setup token
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${{ matrix.environment }}" == "npm-gpr" ]]; then
            echo "NODE_AUTH_TOKEN=${GH_TOKEN}" >> "${GITHUB_ENV}"
          fi

      - name: Setup node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238  # v6.2.0
        with:
          node-version: latest
          registry-url: ${{ matrix.registry-url }}
          scope: '@lizardbyte'

      - name: Strip version prefix
        id: version
        env:
          INPUT_RELEASE_VERSION: ${{ inputs.release_version }}
        run: echo "version=${INPUT_RELEASE_VERSION#v}" >> "${GITHUB_OUTPUT}"

      - name: Update package.json
        env:
          RELEASE_VERSION: ${{ steps.version.outputs.version }}
        run: npm version "${RELEASE_VERSION}" --no-git-tag-version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Publish
        run: npm publish ${{ matrix.extra-args }}

      - name: Set environment output
        id: environment
        run: |
          if [[ "${{ matrix.environment }}" == "npm-gpr" ]]; then
            url="https://github.com/${{ github.repository }}/pkgs/npm/${{ github.event.repository.name }}"
          elif [[ "${{ matrix.environment }}" == "npmjs" ]]; then
            package_name=$(node -p "require('./package.json').name")
            url="https://www.npmjs.com/package/${package_name}"
          fi
          echo "url=${url}" >> "${GITHUB_OUTPUT}"
